# -*- mode: makefile -*- 

######################################################################
# Directories
######################################################################
#
# Installation directory prefix
#
# binaries will be looked in $(XXX_PREFIX)/bin,
# C include files in $(XXX_PREFIX)/include,
# C libraries and OCaml object files and libraries
# in $(PREFIX_INSTALL)/lib

# Where to find smtlib2
#
SMTLIB2_PREFIX = ../smtlib2parser-1.4

######################################################################
# Tools and Flags
######################################################################

# C compiler
CC = gcc

# C compilation flags 
CFLAGS = \
-Wcast-qual -Wswitch -Werror-implicit-function-declaration \
-Wall -Wextra -Wundef -Wbad-function-cast -Wcast-align -Wstrict-prototypes \
-Wno-unused -Wunused-parameter \
-std=c99 -U__STRICT_ANSI__ \
-fPIC -O3 -DNDEBUG -DNDEBUG1 -DNDEBUG2

# C compilation flags in debug (or profile) mode
CFLAGS_DEBUG = \
-Wcast-qual -Wswitch -Werror-implicit-function-declaration \
-Wall -Wextra -Wundef -Wbad-function-cast -Wcast-align -Wstrict-prototypes \
-Wno-unused -Wunused-parameter \
-std=c99  -U__STRICT_ANSI__ \
-fPIC -g -UNDEBUG -UNDEBUG1 -UNDEBUG2

# C++ compiler
CXX = g++
# C++ compilation flags
CXXFLAGS = \
-std=c++11 \
-Wcast-qual -Wswitch \
-Wall -Wextra -Wundef -Wcast-align \
-Wno-unused \
-O3 -DNDEBUG
# C++ compilation flags in debug (or profile) mode
CXXFLAGS_DEBUG = \
-std=c++11 \
-Wcast-qual -Wswitch \
-Wall -Wextra -Wundef -Wcast-align \
-Wno-unused \
-g -O0 -UNDEBUG

AR = ar
RANLIB = ranlib
SED = sed
M4 = m4
INSTALL = install
INSTALLd = install -d

LATEX=latex
DVIPDF=dvipdf
MAKEINDEX=makeindex
TEXI2DVI=texi2dvi
TEXI2HTML=texi2html

FLEX=flex
BISON=bison

